export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY";
export const SET_CURRENT_SUBCATEGORY = "SET_CURRENT_SUBCATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
// export const GET_SUBCATEGORIES = "GET_SUBCATEGORIES";
